### ISSUE TITLE
My miniproject1 idea

### ISSUE THREAD

**Issue by NehPatel2000** [rs1856tn/MiniProject1#1]
I am thinking about comparing two history of soccer websites I found and then compare the same author text with the same history site and another article about soccer formations. I will use beautiful soup to get the important text and then do text analysis. I will compare what top 20 words the two websites have in common and then graph it using matplotlib.

**Comment by rs1856tn** [comment]
Had a pretty similar idea but to contrast language about the PGA Tour and LIV golf on two different websites
